### ISSUE TITLE
Week 4 Cultural

### ISSUE THREAD

**Issue by Hinkdogg** [tsabend/tsabend.github.io#1]
Your week 4 cultural blog was very informative. I didn't realize how primitive SR really was because Siri seems pretty advanced to me. Your blog really taught me how far SR needs to come, before we can really take advantage of it. The thing I liked most about your blog though, was your passion. You really seemed to be interested in this topic and thorough in your research. Great week 4 blog post and keep up the good work!

**Comment by tsabend** [comment]
Thanks for reading!
