### ISSUE TITLE
Week 4 Technical

### ISSUE THREAD

**Issue by samanthadrago** [tsabend/tsabend.github.io#2]
Hey Thomas,

First off, really nice looking blog! Where did you grow up in MA? (I'm from the Cape originally, though now live in San Francisco).

Your explanation of the map method was really clear and helpful to me. I've been struggling with what "enumerable methods" really are. I'm still not clear on when you'd use map instead of each - do you have any thoughts on that? Thanks for a great post!

**Comment by tsabend** [comment]
Hey Samantha,

Thanks for checking out my post. I grew up in Carlisle but my grandparents have a house in Eastham, so I was on the cape for summers. Are you doing DBC in SF?
